 -- Table for storing information about countries
    CREATE TABLE Countries (
        country_id INT PRIMARY KEY,
        country_name VARCHAR(100) NOT NULL
    );
    
    -- Table for storing information about chocolate products
    CREATE TABLE Products (
        product_id INT PRIMARY KEY,
        product_name VARCHAR(100) NOT NULL,
        brand VARCHAR(100) NOT NULL
    );
    
    -- Table for storing information about sales
    CREATE TABLE Sales (
        sale_id INT PRIMARY KEY,
        product_id INT NOT NULL,
        country_id INT NOT NULL,
        sale_date DATE NOT NULL,
        quantity_sold INT NOT NULL,
        revenue DECIMAL(10, 2) NOT NULL,
        FOREIGN KEY (product_id) REFERENCES Products(product_id),
        FOREIGN KEY (country_id) REFERENCES Countries(country_id)
    );
    
    INSERT INTO Countries (country_id, country_name) VALUES
    (1, 'United States'),
    (2, 'United Kingdom'),
    (3, 'Canada'),
    (4, 'Australia'),
    (5, 'Germany'),
    (6, 'France'),
    (7, 'Italy'),
    (8, 'Spain'),
    (9, 'Japan'),
    (10, 'China'),
    (11, 'India'),
    (12, 'Brazil'),
    (13, 'Mexico'),
    (14, 'South Korea'),
    (15, 'Netherlands'),
    (16, 'Switzerland'),
    (17, 'Sweden'),
    (18, 'Norway'),
    (19, 'Denmark'),
    (20, 'Finland'),
    (21, 'Belgium'),
    (22, 'Austria'),
    (23, 'Portugal'),
    (24, 'Greece'),
    (25, 'Ireland'),
    (26, 'New Zealand'),
    (27, 'South Africa'),
    (28, 'Singapore'),
    (29, 'Hong Kong'),
    (30, 'Malaysia'),
    (31, 'Thailand'),
    (32, 'Philippines'),
    (33, 'Vietnam'),
    (34, 'Indonesia'),
    (35, 'Argentina'),
    (36, 'Chile'),
    (37, 'Colombia'),
    (38, 'Peru'),
    (39, 'Turkey'),
    (40, 'Russia'),
    (41, 'Poland'),
    (42, 'Hungary'),
    (43, 'Czech Republic'),
    (44, 'Romania'),
    (45, 'Ukraine'),
    (46, 'Egypt'),
    (47, 'Saudi Arabia'),
    (48, 'United Arab Emirates'),
    (49, 'Israel'),
    (50, 'Pakistan');
    
    INSERT INTO Products (product_id, product_name, brand) VALUES
    (1, 'Dairy Milk', 'Cadbury'),
    (2, 'Hershey''s Milk Chocolate', 'Hershey''s'),
    (3, 'Milka', 'Milka'),
    (4, 'Lindt Excellence', 'Lindt'),
    (5, 'Ghirardelli Intense Dark', 'Ghirardelli'),
    (6, 'Toblerone', 'Toblerone'),
    (7, 'Ferrero Rocher', 'Ferrero'),
    (8, 'Godiva Dark Chocolate', 'Godiva'),
    (9, 'Green & Black''s Organic Chocolate', 'Green & Black''s'),
    (10, 'KitKat', 'Nestlé'),
    (11, 'Snickers', 'Mars'),
    (12, 'Twix', 'Mars'),
    (13, 'M&M''s', 'Mars'),
    (14, 'Cadbury Silk', 'Cadbury'),
    (15, 'Cadbury Bournville', 'Cadbury'),
    (16, 'Cadbury Fuse', 'Cadbury'),
    (17, 'Terry''s Chocolate Orange', 'Terry''s'),
    (18, 'Nestlé Crunch', 'Nestlé'),
    (19, 'Cadbury Flake', 'Cadbury'),
    (20, 'Cadbury Dairy Milk Silk Oreo', 'Cadbury'),
    (21, 'Nestlé Milkybar', 'Nestlé'),
    (22, 'Nestlé Toll House Chocolate Chips', 'Nestlé'),
    (23, 'Cadbury Caramello', 'Cadbury'),
    (24, 'Lindt Lindor', 'Lindt'),
    (25, 'Cadbury Dairy Milk Fruit & Nut', 'Cadbury'),
    (26, 'Cadbury Dairy Milk Roast Almond', 'Cadbury'),
    (27, 'Cadbury Dairy Milk Silk', 'Cadbury'),
    (28, 'Cadbury 5 Star', 'Cadbury'),
    (29, 'Cadbury Perk', 'Cadbury'),
    (30, 'Cadbury Dairy Milk Crackle', 'Cadbury'),
    (31, 'Cadbury Bournvita', 'Cadbury'),
    (32, 'Cadbury Choclairs Gold', 'Cadbury'),
    (33, 'Cadbury Gems', 'Cadbury'),
    (34, 'Cadbury 3 Wishes', 'Cadbury'),
    (35, 'Cadbury Fuse Chocolicious', 'Cadbury'),
    (36, 'Cadbury Temptations', 'Cadbury'),
    (37, 'Cadbury Dairy Milk Silk Bubbly', 'Cadbury'),
    (38, 'Cadbury Dairy Milk Shots', 'Cadbury'),
    (39, 'Cadbury Celebrations', 'Cadbury'),
    (40, 'Cadbury Dairy Milk Miniatures', 'Cadbury'),
    (41, 'Cadbury Perk Cashew', 'Cadbury'),
    (42, 'Cadbury Dairy Milk Silk Hazelnut', 'Cadbury'),
    (43, 'Cadbury Dairy Milk Lickables', 'Cadbury'),
